StockMarketApp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Stocks.urls')),
]

Stocks/urls.py
from django.urls import path
from Stocks import views

app_name = "stock_market"

urlpatterns = [

    path('', views.home_view, name='home'),
    path('stock/<str:stock_ticker>/', views.stock_view, name='stock_view_url'),
    path('signup/', views.sign_up_view, name='sign_up_view'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view')

]

Stocks/models.py
# Create your models here.

Stocks/forms.py
from django import forms


# Stock ticker form
class StockTickerForm(forms.Form):
    ticker = forms.CharField(label='', max_length=5, required=True)
    # Django forms do not include <form> tag or submit button, we have to add them ourselves in the template


# User form for sign up
class SignUpForm(forms.Form):
    email = forms.EmailField(label='', required=True)
    username = forms.CharField(label='', max_length=15, required=True)
    password = forms.CharField(label='', max_length=20, required=True)


class LoginForm(forms.Form):
    username = forms.CharField(label='', max_length=15, required=True)
    password = forms.CharField(label='', max_length=20, required=True)

Stocks/views.py
import datetime
import os
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
import requests
import finnhub
from .forms import StockTickerForm, SignUpForm, LoginForm
from django.contrib.auth.models import User
from dotenv import find_dotenv, load_dotenv

load_dotenv(find_dotenv('.env'))

#############################################################################################

# Configure API key for finnhub API
configuration = finnhub.Configuration(
    api_key={
        'token': os.environ['DjangoStockMarketAppFinnhubAPIKEY']
    }
)
finnhub_client = finnhub.DefaultApi(finnhub.ApiClient(configuration))


#############################################################################################

# Create your views here.

def home_view(request):
    context = {
        "forex_news": finnhub_client.general_news('forex', min_id=0),
        "general_news": finnhub_client.general_news('general', min_id=0),
        "merger_news": finnhub_client.general_news('merger', min_id=0),
        "crypto_news": finnhub_client.general_news('crypto', min_id=0)
    }

    if request.user.is_authenticated:
        context["Username"] = request.user

    # If the form is filled (i.e. it is a POST request), verify the input and redirect, otherwise stay on the same page
    if request.method == 'POST':

        # Checking which button was clicked so we can know which form has been submitted. The button in the HTML
        # template that submits the form must have a 'name' and 'value' which represent a 'key'-'value' pair in the
        # request.POST dictionary

        if 'SearchButtonForm' in request.POST:
            Searchform = StockTickerForm(request.POST)  # Bind the form to data to be able to perform validation after

            if Searchform.is_valid():
                uppercase_ticker = Searchform.cleaned_data['ticker'].upper()
                return HttpResponseRedirect(reverse('stock_market:stock_view_url', args=[uppercase_ticker]))

    else:  # else it is a GET request
        Searchform = StockTickerForm()  # Empty search form
        context['Searchform'] = Searchform  # Add empty search form to context

    return render(request, 'Stocks/base.html', context)


#####################################################################################################################

def stock_view(request, stock_ticker):
    context = {
        'ticker': stock_ticker,
        'company_profile': finnhub_client.company_profile2(symbol=stock_ticker),
        'quote': finnhub_client.quote(stock_ticker),
    }

    # If the form is filled (i.e. it is a POST request), verify the input and redirect, otherwise stay on the same page
    if request.method == 'POST':

        if 'SearchButtonForm' in request.POST:
            Searchform = StockTickerForm(request.POST)  # Bind the form to data to be able to perform validation after

            if Searchform.is_valid():
                uppercase_ticker = Searchform.cleaned_data['ticker'].upper()
                return HttpResponseRedirect(reverse('stock_market:stock_view_url', args=[uppercase_ticker]))

    else:  # else it is a GET request
        Searchform = StockTickerForm()  # Empty search form

        # Getting company basics financials
        r = requests.get(
            f"https://finnhub.io/api/v1/stock/metric?symbol={stock_ticker}&metric=all&token={os.environ.get('DjangoStockMarketAppFinnhubAPIKEY')}")
        data = r.json()

        # Dates for company news
        now = datetime.datetime.now()
        year = '{:02d}'.format(now.year)
        month = '{:02d}'.format(now.month)
        day = '{:02d}'.format(now.day)
        year_month_day2 = '{}-{}-{}'.format(year, month, day)

        year1 = '{:02d}'.format(now.year - 1)
        year_before = '{:02d}'.format(now.month - 12)
        year_month_day1 = '{}-{}-{}'.format(year1, year_before, day)

        # Getting news from 1 year prior to now
        company_news = finnhub_client.company_news(stock_ticker, _from=year_month_day1, to=year_month_day2)

        context['company_news'] = company_news
        context['basic_financials'] = data
        context['Searchform'] = Searchform

    return render(request, 'Stocks/StockView.html', context)


##################################################################################################################

def sign_up_view(request):
    context = {}

    if request.method == 'POST':
        if "SearchButtonForm" in request.POST:
            Searchform = StockTickerForm(request.POST)

            if Searchform.is_valid():
                uppercase_ticker = Searchform.cleaned_data['ticker'].upper()
                return HttpResponseRedirect(reverse('stock_market:stock_view_url', args=[uppercase_ticker]))

        elif "SignUpButton" in request.POST:
            signUpForm = SignUpForm(request.POST)

            if signUpForm.is_valid():
                # Fetching form data
                email = signUpForm.cleaned_data['email']
                username = signUpForm.cleaned_data['username']
                password = signUpForm.cleaned_data['password']

                if User.objects.filter(username=signUpForm.cleaned_data['username']):
                    messages.add_message(request, messages.ERROR, 'Username already taken!')
                    context["SignUpform"] = signUpForm
                    context["Searchform"] = StockTickerForm()
                    return render(request, 'Stocks/SignUpView.html', context)

                else:
                    # Create a new user from Member model object and save it to the database
                    member = User.objects.create_user(email=email, username=username, password=password)
                    member.save()

                    login(request, member)  # login the created user and redirect

                    return HttpResponseRedirect(reverse('stock_market:home'))

    else:

        context["SignUpform"] = SignUpForm()
        context["Searchform"] = StockTickerForm()

        return render(request, 'Stocks/SignUpView.html', context)


###################################################################################################################

def login_view(request):
    context = {}

    if request.method == 'GET':
        loginform = LoginForm()
        searchform = StockTickerForm()
        context['LoginForm'] = loginform
        context['Searchform'] = searchform
        return render(request, 'Stocks/LoginView.html', context)

    elif request.method == 'POST':

        # If the user searches for a stock ticker (even though they shouldn't)
        if "SearchButtonForm" in request.POST:
            Searchform = StockTickerForm(request.POST)

            if Searchform.is_valid():
                uppercase_ticker = Searchform.cleaned_data['ticker'].upper()
                return HttpResponseRedirect(reverse('stock_market:stock_view_url', args=[uppercase_ticker]))

        else:

            loginform = LoginForm(request.POST)

            if loginform.is_valid():

                username1 = request.POST['username']
                password1 = request.POST['password']

                # Validate user credentials
                user = authenticate(request, username=username1, password=password1)

                if user is not None:
                    login(request, user)
                    # Redirect to home page
                    return HttpResponseRedirect(reverse('stock_market:home'))

                else:
                    # Display an error message
                    messages.add_message(request, messages.ERROR, "Invalid credentials!")
                    context['LoginForm'] = loginform
                    searchform = StockTickerForm()
                    context['Searchform'] = searchform
                    return render(request, 'Stocks/LoginView.html', context)


################################################################################################################

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('stock_market:home'))

Stocks/templates/Stocks/Crypto_News.html
<div class="container-lg col-lg-8 tabcontent" id="Crypto_News">

   {% for news in crypto_news|slice:":50" %}

        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="{{ news.image }}" class="card-img" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{{ news.url }}" target="_blank">{{ news.headline|safe }}</a></h5>
                <p class="card-text">{{ news.summary|truncatewords:100 }}</p>
                <p class="card-text"><small class="text-muted">Date published: </small><small class="text-muted date">{{ news.datetime }}
                                                                                                                                            </small></p>
              </div>
            </div>
          </div>
        </div>

    {% endfor %}

</div>

Stocks/templates/Stocks/Forex_News.html
<div class="container-lg col-lg-8 tabcontent" id="Forex_News">

   {% for news in forex_news|slice:":50" %}

        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">

              {% if news.image %}
                  <img src="{{ news.image }}" class="card-img" alt="">
              {% else %}
                  {% load static %}
                  <img src="{% static 'Stocks/Forex_Image.jpeg' %}" class="card-img" alt="">
              {% endif %}
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{{ news.url }}" target="_blank">{{ news.headline|safe }}</a></h5>
                <p class="card-text">{{ news.summary|truncatewords:100 }}</p>
                <p class="card-text"><small class="text-muted">Date published: </small><small class="text-muted date">{{ news.datetime }}
                                                                                                                                            </small></p>
              </div>
            </div>
          </div>
        </div>

    {% endfor %}

</div>

Stocks/templates/Stocks/General_News.html
<div class="container-lg col-lg-8 tabcontent" id="General_News">

   {% for news in general_news|slice:":50" %}

        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="{{ news.image }}" class="card-img" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{{ news.url }}" target="_blank">{{ news.headline|safe }}</a></h5>
                <p class="card-text">{{ news.summary|truncatewords:100 }}</p>
                <p class="card-text"><small class="text-muted">Date published: </small><small class="text-muted date">{{ news.datetime }}
                                                                                                                                            </small></p>
              </div>
            </div>
          </div>
        </div>

    {% endfor %}

</div>

Stocks/templates/Stocks/LoginView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Including bootstrap -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'Stocks/SignUp&LoginView.css' %}">

    <title>Login</title>

</head>
<body>

{% include "Stocks/navbar.html" %}

<div class="container-lg col-lg-4">

    <form method="post" action="" id="LoginForm">

        {% if messages %}

            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}

        {% endif %}

        {% csrf_token %}

        {% load widget_tweaks %}

        <div class="form-group">
            {% render_field LoginForm.username class+="form-control" type="text" placeholder="Username" %}
        </div>

        <div class="form-group">
            {% render_field LoginForm.password class+="form-control" type="password" placeholder="password" %}
        </div>

        <button type="submit" class="btn btn-primary" name="LoginButton" value="LoginButton">Login</button>

    </form>

</div>


 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

Stocks/templates/Stocks/Merger_News.html
<div class="container-lg col-lg-8 tabcontent" id="Merger_News">

   {% for news in merger_news|slice:":50" %}

        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="{{ news.image }}" class="card-img" alt="">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{{ news.url }}" target="_blank">{{ news.headline|safe }}</a></h5>
                <p class="card-text">{{ news.summary|truncatewords:100 }}</p>
                <p class="card-text"><small class="text-muted">Date published: </small><small class="text-muted date">{{ news.datetime }}
                                                                                                                                            </small></p>
              </div>
            </div>
          </div>
        </div>

    {% endfor %}

</div>

Stocks/templates/Stocks/SignUpForm.html
              <!-- Sign up form -->
          <form method="post" action="" id="SignUpForm">

              {% if messages %}

                    {% for message in messages %}

                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>

                    {% endfor %}

                {% endif %}

              {% csrf_token %}

            {% load widget_tweaks %}

            <div class="form-group">
                {% render_field SignUpform.email class+="form-control" type="email" placeholder="Email address" %}
            </div>

            <div class="form-group">
                {% render_field SignUpform.username class+="form-control" type="text" placeholder="Username" %}
            </div>

            <div class="form-group">
                {% render_field SignUpform.password class+="form-control" type="password" placeholder="password" %}
            </div>

            <button type="submit" class="btn btn-primary" name="SignUpButton" value="SignUpButton">Sign Up</button>

        </form>

Stocks/templates/Stocks/SignUpView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Including bootstrap -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'Stocks/SignUp&LoginView.css' %}">

    <title>Sign Up</title>

</head>
<body>

{% include "Stocks/navbar.html" %}

<div class="container-xl col-xl-4">

    {% include "Stocks/SignUpForm.html" %}

</div>


 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

Stocks/templates/Stocks/StockView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Including bootstrap -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--Link to chart.js CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css">


    <title id="title">{{ ticker }}</title>

</head>
<body>


{% include "Stocks/navbar.html" %}


<div class="container-lg col-lg-8 tab">

    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="StockViewTabsNavbar">

        <!-- Sandwich button -->
        <button class="navbar-toggler mr-sm-2" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <button class="tablinks" id="Summary_button" onclick="openTab(this.id, 'Summary_content')">Summary</button>
            <button class="tablinks" id="Recommendations_button" onclick="openTab(this.id, 'Recommendations_content')">Recommendations</button>
            <button class="tablinks" id="Price_target_button" onclick="openTab(this.id, 'Price_Target_content')">Price Target</button>
        </div>
    </nav>

</div> <!--End of container -->


<!-- 'Summary' tab -->
<div class="container-xl col-xl-8 tabcontent" id="Summary_content">
{% load humanize %}

    <h5>{{ company_profile.name }} -- {{ ticker }} ({{ company_profile.exchange }})</h5>
    <p><small>Currency: {{ company_profile.currency }} -- Country: {{ company_profile.country }} -- Industry: {{ company_profile.finnhub_industry }}</small></p>

    <h2 id="CurrentQuote">{{ quote.c|intcomma }}</h2>

    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Stock</th>
      <th scope="col">Info</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Previous close: {{ quote.pc|intcomma }}</td>
      <td>Market Cap (in millions):  {{ company_profile.market_capitalization|intcomma }}</td>
    </tr>
    <tr>
      <td id="Open">Open: {{ quote.o|intcomma }}</td>
      <td>Outstanding shares (in millions):  {{ company_profile.share_outstanding|intcomma }}</td>
    </tr>
    <tr>
      <td id="High">High: {{ quote.h|intcomma }}</td>
      <td>10 Day avg trading volume (in millions): {{ basic_financials.metric.10DayAverageTradingVolume|intcomma }}</td>
    </tr>
    <tr>
      <td id="Low">Low: {{ quote.l|intcomma }}</td>
      <td>52 week high: {{ basic_financials.metric.52WeekHigh|intcomma }}</td>
    </tr>
    <tr>
      <td>3 month avg trading volume (in millions): {{ basic_financials.metric.3MonthAverageTradingVolume|intcomma }}</td>
      <td>52 week low: {{ basic_financials.metric.52WeekLow|intcomma }}</td>
    </tr>
    <tr>
      <td>13 week price return daily: {{ basic_financials.metric.13WeekPriceReturnDaily|intcomma }}</td>
      <td>URL: <a href="{{ company_profile.weburl }}" target="_blank">{{ company_profile.weburl }}</a></td>
    </tr>
  </tbody>
</table>


<!--Company News -->

{% for news in company_news|slice:":50" %}

<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{% if news.image %}
        {{ news.image }} {% else %} {{ company_profile.logo  }} {% endif %}" class="card-img" alt="">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{ news.url }}" target="_blank">{{ news.headline | safe }}</a></h5>
        <p class="card-text">{{ news.summary|truncatewords:100 }}</p>
        <p class="card-text"><small class="text-muted">Date published: </small><small class="text-muted date">{{ news.datetime }}</small></p>
      </div>
    </div>
  </div>
</div>

{% endfor %}
</div> <!-- End of 'Summary' tab -->



<!-- 'Recommendations tab' tab -->
<div class="wrapper">
    <div class="container-lg col-lg-8 tabcontent" id="Recommendations_content">

        <!--Canvas for charts -->
        <canvas id="StockRecommendations"></canvas>

    </div>
</div>
<!-- End of 'Recommendations tab' tab -->


<!-- 'Price Target' tab -->

    <div class="container-lg col-lg-8 tabcontent wrapper" id="Price_Target_content">

        <!--Canvas for charts -->
        <canvas id="PriceTargets"></canvas>

    </div>

<!-- End of 'Price Target' tab -->



{% load static %}
    <link rel="stylesheet" href="{% static "Stocks/StockView.css" %}">
    <script src="{% static "Stocks/StockViewTabs.js" %}"></script>
    <script src="{% static "Stocks/Recommendations_Chart.js" %}"></script>
    <script src="{% static "Stocks/Price_Target_Chart.js" %}"></script>
    <script src="{% static 'Stocks/UnixTimeConversionMethod.js' %}"></script>

<script>
        // Get the element with id="defaultOpen" and click on it
        document.getElementById("Summary_button").click();

        window.onload = function(){
            Convert();
        }
        let d = new Date();
        if(d.getDay() !== 0 && d.getDay() !== 6 && d.getHours() < 16 && d.getHours() > 9) {
            //Update the stock price each 3 second interval
            window.setInterval(update_Price, 3000);
        }
</script>



<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

Stocks/templates/Stocks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Including bootstrap -->

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Stocks</title>

</head>
<body onload="Convert()">

{% include "Stocks/navbar.html" %}

<div class="container-xl col-xl-8 tab">

    <nav class="navbar navbar-expand-xl navbar-light bg-light" id="StockViewTabsNavbar">

        <!-- Sandwich button -->
        <button class="navbar-toggler mr-sm-2" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <button type="button" class="tabButton" id="GeneralNewsButton" onclick="changeNewsTab(this.id, 'General_News')">General</button>
            <button type="button" class="tabButton" id="MergerNewsButton" onclick="changeNewsTab(this.id, 'Merger_News')">Crypto</button>
            <button type="button" class="tabButton" id="CryptoNewsButton" onclick="changeNewsTab(this.id, 'Crypto_News')">Merger</button>
            <button type="button" class="tabButton" id="ForexNewsButton" onclick="changeNewsTab(this.id, 'Forex_News')">Forex</button>
        </div>
    </nav>



</div>


{% include 'Stocks/Merger_News.html' %}


{% include 'Stocks/Crypto_News.html' %}

{% include 'Stocks/Forex_News.html' %}


{% include 'Stocks/General_News.html' %}



    {% load static %}
    <script src="{% static 'Stocks/UnixTimeConversionMethod.js' %}"></script>
    <link rel="stylesheet" href="{% static 'Stocks/Navbar.css' %}">
    <link rel="stylesheet" href="{% static 'Stocks/HomePageNews.css' %}">
    <script src="{% static 'Stocks/HomePageNews.js' %}"></script>

    <script>
        document.getElementById('GeneralNewsButton').click();
    </script>


 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

Stocks/templates/Stocks/navbar.html
<!-- Creating navigation bar -->

<nav class="navbar navbar-expand-xl navbar-light bg-light">
    <a class="navbar-brand" href="#">StocksOnly</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbarContent">

        <ul class="navbar-nav ">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'stock_market:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

        </ul>

        <form class="form-inline mx-auto my-2 my-lg-0" name="stock_ticker_form" action="" method="post">
            {% csrf_token %}

            {% load widget_tweaks %}

            {% render_field Searchform.ticker class+="form-control mr-sm-2" type="search" placeholder="Search Stock Symbol" aria-label="Search" %}

            <button class="btn btn-outline-success my-2 my-sm-0" name="SearchButtonForm" type="submit" value="SearchButtonForm">Search</button>

        </form>


        {% if Username %}

            <a href="" id="username_tag">{{ Username }}</a>
            <a href="{% url 'stock_market:logout_view' %}" class="btn btn-primary">logout</a>

        {% else %}

            <a href="{% url 'stock_market:login_view' %}" class="btn btn-outline-primary mx-1 my-2 my-sm-0">Login</a>
            <a href="{% url 'stock_market:sign_up_view' %}" class="btn btn-primary">Sign Up</a>

        {% endif %}
    </div>

</nav>